config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  resources :librarians
  resources :books
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/librarian.rb
class Librarian < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author)
    end
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
    before_action :set_librarian, only: %i[show edit update destroy]
    before_action :authenticate_user!, except: %i[show index]
    def index
        @librarians = Librarian.all
    end
    
    def show
    end

    def edit
    end

    def new 
        @librarian = Librarian.new
    end
    
    def create
        @librarian = Librarian.new(librarian_params)
        if @librarian.save
            redirect_to @librarian, notice: "New librarian was successfully"
        else
            render "new"
        end
    end

    def update
        if @librarian.update(librarian_params) 
            redirect_to librarian_url(@librarian), notice: "Edit libirarians was successfully"
        else 
            redirect_to librarian_url(@librarian), notice: "Edit was not successful"
        end
    end

    def destroy
        @librarian.destroy
        redirect_to @librarian, notice: "Destroy librarian was successfully"
    end
    
    private
    def set_librarian
        @librarian = Librarian.find(params[:id]) 
    end

    def librarian_params
        params.require(:librarian).permit(:name, :age)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/librarian_helper.rb
module LibrarianHelper
    def format_name(librarian)
        if librarian.age >= 18
            "Mr. #{librarian.name}"
        else
            "#{librarian.name}"
        end
    end
end

app/views/admin/home.html.erb
<h1>Admin page</h1>
Welcome to Admin

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Name:</strong>
    <%= book.name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Author</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @books.each do |book| %>
     <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= link_to "Show Book", book %></td>
    </tr>
  <% end %>
    </tr>
  </tbody>
</table>
<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Admin", root_path, class:"navbar-brand"%>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Books", books_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Librarian", librarians_path, class:"nav-link active"%>
        </li>
        <% if user_signed_in?%>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-secondary"%>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link active"%>
        </li>
        <% end %>
       </ul>
    </div>
  </div>
</nav> 

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Admin App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom.css"%>
  </head>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end%>

    <%= render 'home/header'%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/librarians/_form.html.erb
<%= form_with(model: @librarian) do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :age%>
    <%= f.number_field :age%>

    <%= f.submit yield(:button_text), class:'btn btn-primary'%>
<% end %>

app/views/librarians/_librarian.html.erb
<div id="<%= dom_id librarian%>">
    <p>
        <strong>Name:</strong>
        <%= format_name(librarian)%>
    </p>
    <p>
        <strong>Age:</strong>
        <%= librarian.age%>
    </p>
</div>

app/views/librarians/edit.html.erb
<%= form_with(model: @librarian) do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :age%>
    <%= f.number_field :age%>

    <%= f.submit yield(:button_text), class:'btn btn-primary'%>
<% end %>

app/views/librarians/index.html.erb
<h1>Librarian</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Author</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @librarians.each do |librarian| %>
        <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.age %></td>
        <td><%= link_to "Show librarian", librarian %></td>
        </tr>
    <% end %>
    </tr>
  </tbody>
</table>
<%= link_to "New librarian", new_librarian_path%>

app/views/librarians/new.html.erb
<h1>New librarians</h1>

<%= render "form", librarians: @librarians%>

<br>

<div>
    <%link_to "Back to librarians", librarians_path%>

app/views/librarians/show.html.erb
<%= render @librarian%>

<%= link_to "Edit librarian", edit_librarian_path(@librarian)%>
<%= button_to "Delete librarian", @librarian, method: :delete, class: "btn btn-danger"%>